### PR TITLE
Minor tweaks and clarifications

### PR DESCRIPTION
**Pull request by HenrikBengtsson**
Nice introduction.  I've made some minor tweaks.

Yesterday, I learned about @gaborcsardi's [r-bug proposal](https://github.com/r-hub/proposal).  It would be amazing if that gets supported; you may want to mention that the proposal exists in your talk.

### CODE REVIEW

**Comment by PeteHaitch** [comment]
Thanks, Henrik. I hadn't seen the ~~r-bug~~ r-hub proposal - wow, it'd be great if it gets up. I probably won't include in my talk, but just mention that there are smarter people than me looking into this greater topic.

**Comment by gaborcsardi** [comment]
Great presentation! 

I am not sure if `r-bug` was a typo or an intentional nickname. If the former, then the name is `r-hub`. Hopefully it won't have enough bugs to call it `r-bug`. :)

**Comment by PeteHaitch** [comment]
Haha, sorry! Excited to follow the progress of r-hub :)

**Comment by HenrikBengtsson** [comment]
My bad :)

**Pull request merged**
